# Disabled because it takes too long. Built locally and uploaded instead
# on:
#   push:
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/checkout@v2
      - name: Create archives
        run: |
          sudo add-apt-repository ppa:ubuntugis/ppa
          sudo apt-get update
          sudo apt install pngquant zopfli gdal-bin squashfs-tools
          make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Fonts.squashfs
            ShadedReliefBasic.squashfs
            NaturalEarthShadedRelief.squashfs
            GrayEarthShadedRelief.squashfs
